Update hydroserver_gcp_deployment.yml

diff --git a/.github/workflows/hydroserver_gcp_deployment.yml b/.github/workflows/hydroserver_gcp_deployment.yml
--- a/.github/workflows/hydroserver_gcp_deployment.yml
+++ b/.github/workflows/hydroserver_gcp_deployment.yml
@@ -66,7 +66,7 @@ jobs:
     environment: ${{ github.event.inputs.environment }}
     defaults:
       run:
-        working-directory: ./terraform/gcp/network
+        working-directory: ./terraform/gcp/app
     steps:
       - name: Checkout Ops Repo
         uses: actions/checkout@v4
@@ -85,12 +85,16 @@ jobs:
           terraform init \
           -backend-config="impersonate_service_account=${{ vars.GCP_SERVICE_ACCOUNT }}" \
           -backend-config="bucket=${{ vars.TERRAFORM_BUCKET }}" \
-          -backend-config="prefix=state/hydroserver_network_${{ github.event.inputs.environment }}"
+          -backend-config="prefix=state/hydroserver_application_${{ github.event.inputs.environment }}"
       - name: Terraform Plan
         id: plan
         run: |
           terraform plan \
           -no-color -input=false \
+          -target=google_compute_network.vpc_network \
+          -target=google_compute_global_address.private_service_ip \
+          -target=google_service_networking_connection.private_service_connection \
+          -target=google_vpc_access_connector.vpc_access_connector \
           -var "instance=${{ github.event.inputs.environment }}" \
           -var "region=${{ vars.GCP_REGION }}" \
           -var "project_id=${{ vars.GCP_PROJECT_ID }}" \
@@ -104,6 +108,10 @@ jobs:
         run: |
           terraform apply \
           -auto-approve -input=false \
+          -target=google_compute_network.vpc_network \
+          -target=google_compute_global_address.private_service_ip \
+          -target=google_service_networking_connection.private_service_connection \
+          -target=google_vpc_access_connector.vpc_access_connector \
           -var "instance=${{ github.event.inputs.environment }}" \
           -var "region=${{ vars.GCP_REGION }}" \
           -var "project_id=${{ vars.GCP_PROJECT_ID }}" \
@@ -376,47 +384,47 @@ jobs:
           -var region="${{ vars.GCP_REGION }}" \
           -var project_id="${{ vars.GCP_PROJECT_ID }}"
 
-  teardown-hydroserver-network:
-    needs: teardown-hydroserver-services
-    runs-on: ubuntu-latest
-    environment: ${{ github.event.inputs.environment }}
-    if: success() && github.event.inputs.action == 'Teardown HydroServer Deployment'
-    defaults:
-      run:
-        working-directory: ./terraform/gcp/network
-    steps:
-      - name: Checkout Ops Repo
-        uses: actions/checkout@v4
-        with:
-          ref: main
-      - name: Configure GCP Credentials
-        uses: google-github-actions/auth@v2
-        with:
-          project_id: ${{ vars.GCP_PROJECT_ID }}
-          workload_identity_provider: ${{ vars.GCP_IDENTITY_PROVIDER }}
-          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v1
-      - name: Terraform Init
-        run: |
-          terraform init \
-          -backend-config="impersonate_service_account=${{ vars.GCP_SERVICE_ACCOUNT }}" \
-          -backend-config="bucket=${{ vars.TERRAFORM_BUCKET }}" \
-          -backend-config="prefix=state/hydroserver_network_${{ github.event.inputs.environment }}"
-      - name: Terraform Plan Destroy
-        id: plan_destroy
-        run: |
-          terraform plan -destroy -no-color -input=false \
-          -var instance="${{ github.event.inputs.environment }}" \
-          -var region="${{ vars.GCP_REGION }}" \
-          -var project_id="${{ vars.GCP_PROJECT_ID }}"
-        continue-on-error: true
-      - name: Terraform Plan Destroy Status
-        if: steps.plan_destroy.outcome == 'failure'
-        run: exit 1
-      - name: Terraform Destroy
-        run: |
-          terraform destroy -auto-approve -input=false \
-          -var instance="${{ github.event.inputs.environment }}" \
-          -var region="${{ vars.GCP_REGION }}" \
-          -var project_id="${{ vars.GCP_PROJECT_ID }}"
+#  teardown-hydroserver-network:
+#    needs: teardown-hydroserver-services
+#    runs-on: ubuntu-latest
+#    environment: ${{ github.event.inputs.environment }}
+#    if: success() && github.event.inputs.action == 'Teardown HydroServer Deployment'
+#    defaults:
+#      run:
+#        working-directory: ./terraform/gcp/network
+#    steps:
+#      - name: Checkout Ops Repo
+#        uses: actions/checkout@v4
+#        with:
+#          ref: main
+#      - name: Configure GCP Credentials
+#        uses: google-github-actions/auth@v2
+#        with:
+#          project_id: ${{ vars.GCP_PROJECT_ID }}
+#          workload_identity_provider: ${{ vars.GCP_IDENTITY_PROVIDER }}
+#          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
+#      - name: Setup Terraform
+#        uses: hashicorp/setup-terraform@v1
+#      - name: Terraform Init
+#        run: |
+#          terraform init \
+#          -backend-config="impersonate_service_account=${{ vars.GCP_SERVICE_ACCOUNT }}" \
+#          -backend-config="bucket=${{ vars.TERRAFORM_BUCKET }}" \
+#          -backend-config="prefix=state/hydroserver_network_${{ github.event.inputs.environment }}"
+#      - name: Terraform Plan Destroy
+#        id: plan_destroy
+#        run: |
+#          terraform plan -destroy -no-color -input=false \
+#          -var instance="${{ github.event.inputs.environment }}" \
+#          -var region="${{ vars.GCP_REGION }}" \
+#          -var project_id="${{ vars.GCP_PROJECT_ID }}"
+#        continue-on-error: true
+#      - name: Terraform Plan Destroy Status
+#        if: steps.plan_destroy.outcome == 'failure'
+#        run: exit 1
+#      - name: Terraform Destroy
+#        run: |
+#          terraform destroy -auto-approve -input=false \
+#          -var instance="${{ github.event.inputs.environment }}" \
+#          -var region="${{ vars.GCP_REGION }}" \
+#          -var project_id="${{ vars.GCP_PROJECT_ID }}"
