Update hydroserver_aws_deployment.yml

diff --git a/.github/workflows/hydroserver_aws_deployment.yml b/.github/workflows/hydroserver_aws_deployment.yml
--- a/.github/workflows/hydroserver_aws_deployment.yml
+++ b/.github/workflows/hydroserver_aws_deployment.yml
@@ -121,86 +121,86 @@ jobs:
           -var "tag_key=${{ vars.AWS_TAG_KEY || 'hydroserver-instance' }}" \
           -var "tag_value=${{ vars.AWS_TAG_VALUE || github.event.inputs.environment }}"
 
-  # deploy-hydroserver-api:
-  #   needs: 
-  #     - check-environment-variables
-  #     - initialize-hydroserver
-  #   if: >
-  #     always() && 
-  #     !contains(needs.*.result, 'failure') &&
-  #     (
-  #       (github.event.inputs.action == 'Initialize HydroServer Deployment' && needs.initialize-hydroserver.result == 'success') ||
-  #       (github.event.inputs.action == 'Update HydroServer Deployment' && needs.check-environment-variables.result == 'success')
-  #     )
-  #   runs-on: ubuntu-latest
-  #   environment: ${{ github.event.inputs.environment }}
-  #   defaults:
-  #     run:
-  #       working-directory: ./terraform/aws
-  #   steps:
-  #     - name: Checkout Ops Repo
-  #       uses: actions/checkout@v4
-  #       with:
-  #         ref: main
-  #     - name: Configure AWS Credentials
-  #       uses: aws-actions/configure-aws-credentials@v4
-  #       with:
-  #         role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_IAM_ROLE }}
-  #         role-session-name: create-hydroserver-resources
-  #         aws-region: ${{ vars.AWS_REGION }}
-  #     - name: Log in to AWS ECR
-  #       run: |
-  #         aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin "${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"
-  #     - name: Pull image from GHCR
-  #       run: |
-  #         docker pull ghcr.io/hydroserver2/hydroserver-api-services:latest
-  #     - name: Tag Docker Image for ECR
-  #       run: |
-  #         docker tag ghcr.io/hydroserver2/hydroserver-api-services:latest \
-  #         ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/hydroserver-api-${{ github.event.inputs.environment }}:latest
-  #     - name: Push Docker Image to AWS ECR
-  #       run: |
-  #         docker push ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/hydroserver-api-${{ github.event.inputs.environment }}:latest
-  #     - name: Update AWS Secrets Manager Values
-  #       run: |
-  #         SECRETS=("DATABASE_URL" "SMTP_URL" "SECRET_KEY")
-  #         SECRET_ARN="arn:aws:secretsmanager:${{ vars.AWS_REGION }}:${{ vars.AWS_ACCOUNT_ID }}:secret:hydroserver-api-${{ github.event.inputs.environment }}"
-  #         for SECRET in "${SECRETS[@]}"; do
-  #           VALUE="${{ secrets[SECRET] }}"
-  #           if [ -n "$VALUE" ]; then
-  #             echo "Updating $SECRET in AWS Secrets Manager..."
-  #             aws secretsmanager update-secret --secret-id "$SECRET_ARN" --secret-string "{\"$SECRET\":\"$VALUE\"}"
-  #           else
-  #             echo "$SECRET is not set, skipping..."
-  #           fi
-  #         done
-  #     - name: Update AWS App Runner Service
-  #       run: |
-  #         APP_RUNNER_SERVICE_NAME="hydroserver-api-${{ github.event.inputs.environment }}"
-  #         SERVICE_ARN=$(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='$APP_RUNNER_SERVICE_NAME'].ServiceArn" --output text)
-  #         if [ -z "$SERVICE_ARN" ]; then
-  #           echo "App Runner service not found: $APP_RUNNER_SERVICE_NAME"
-  #           exit 1
-  #         fi
-  #         echo "Updating AWS App Runner service: $APP_RUNNER_SERVICE_NAME"
-  #         ENV_VARS=()
-  #         [[ -n "${{ vars.PROXY_BASE_URL }}" ]] && ENV_VARS+=("Name=PROXY_BASE_URL,Value=${{ vars.PROXY_BASE_URL }}")
-  #         [[ -n "${{ vars.DEBUG }}" ]] && ENV_VARS+=("Name=DEBUG,Value=${{ vars.DEBUG }}")
-  #         [[ -n "${{ vars.ACCOUNT_SIGNUP_ENABLED }}" ]] && ENV_VARS+=("Name=ACCOUNT_SIGNUP_ENABLED,Value=${{ vars.ACCOUNT_SIGNUP_ENABLED }}")
-  #         [[ -n "${{ vars.ACCOUNT_OWNERSHIP_ENABLED }}" ]] && ENV_VARS+=("Name=ACCOUNT_OWNERSHIP_ENABLED,Value=${{ vars.ACCOUNT_OWNERSHIP_ENABLED }}")
-  #         [[ -n "${{ vars.SOCIALACCOUNT_SIGNUP_ONLY }}" ]] && ENV_VARS+=("Name=SOCIALACCOUNT_SIGNUP_ONLY,Value=${{ vars.SOCIALACCOUNT_SIGNUP_ONLY }}")
-  #         ENV_VARS_STRING=$(IFS=" " ; echo "${ENV_VARS[*]}")
-  #         UPDATE_CMD="aws apprunner update-service --service-arn \"$SERVICE_ARN\" --source-configuration \"{
-  #           \\\"AuthenticationConfiguration\\\": {\\\"AccessRoleArn\\\": \\\"arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/AppRunnerECRAccessRole\\\"},
-  #           \\\"ImageRepository\\\": {
-  #             \\\"ImageIdentifier\\\": \\\"${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/hydroserver-api-${{ github.event.inputs.environment }}:latest\\\",
-  #             \\\"ImageRepositoryType\\\": \\\"ECR\\\"
-  #           }
-  #         }\""
-  #         if [ -n "$ENV_VARS_STRING" ]; then
-  #           UPDATE_CMD="$UPDATE_CMD --environment-variables $ENV_VARS_STRING"
-  #         fi
-  #         eval $UPDATE_CMD
+  deploy-hydroserver-api:
+    needs: 
+      - check-environment-variables
+      - initialize-hydroserver
+    if: >
+      always() && 
+      !contains(needs.*.result, 'failure') &&
+      (
+        (github.event.inputs.action == 'Initialize HydroServer Deployment' && needs.initialize-hydroserver.result == 'success') ||
+        (github.event.inputs.action == 'Update HydroServer Deployment' && needs.check-environment-variables.result == 'success')
+      )
+    runs-on: ubuntu-latest
+    environment: ${{ github.event.inputs.environment }}
+    defaults:
+      run:
+        working-directory: ./terraform/aws
+    steps:
+      - name: Checkout Ops Repo
+        uses: actions/checkout@v4
+        with:
+          ref: main
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_IAM_ROLE }}
+          role-session-name: create-hydroserver-resources
+          aws-region: ${{ vars.AWS_REGION }}
+      - name: Log in to AWS ECR
+        run: |
+          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin "${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"
+      - name: Pull image from GHCR
+        run: |
+          docker pull ghcr.io/hydroserver2/hydroserver-api-services:latest
+      - name: Tag Docker Image for ECR
+        run: |
+          docker tag ghcr.io/hydroserver2/hydroserver-api-services:latest \
+          ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/hydroserver-api-${{ github.event.inputs.environment }}:latest
+      - name: Push Docker Image to AWS ECR
+        run: |
+          docker push ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/hydroserver-api-${{ github.event.inputs.environment }}:latest
+      - name: Update AWS Secrets Manager Values
+        run: |
+          SECRETS=("DATABASE_URL" "SMTP_URL" "SECRET_KEY")
+          SECRET_ARN="arn:aws:secretsmanager:${{ vars.AWS_REGION }}:${{ vars.AWS_ACCOUNT_ID }}:secret:hydroserver-api-${{ github.event.inputs.environment }}"
+          for SECRET in "${SECRETS[@]}"; do
+            VALUE="${{ secrets[SECRET] }}"
+            if [ -n "$VALUE" ]; then
+              echo "Updating $SECRET in AWS Secrets Manager..."
+              aws secretsmanager update-secret --secret-id "$SECRET_ARN" --secret-string "{\"$SECRET\":\"$VALUE\"}"
+            else
+              echo "$SECRET is not set, skipping..."
+            fi
+          done
+      - name: Update AWS App Runner Service
+        run: |
+          APP_RUNNER_SERVICE_NAME="hydroserver-api-${{ github.event.inputs.environment }}"
+          SERVICE_ARN=$(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='$APP_RUNNER_SERVICE_NAME'].ServiceArn" --output text)
+          if [ -z "$SERVICE_ARN" ]; then
+            echo "App Runner service not found: $APP_RUNNER_SERVICE_NAME"
+            exit 1
+          fi
+          echo "Fetching current environment variables for App Runner service: $APP_RUNNER_SERVICE_NAME"
+          CURRENT_ENV_VARS=$(aws apprunner describe-service --service-arn "$SERVICE_ARN" --query "Service.State.SourceConfiguration.EnvironmentVariables" --output json)      
+          ENV_VARS=()      
+          [[ -n "${{ vars.PROXY_BASE_URL }}" ]] && ENV_VARS+=("Name=PROXY_BASE_URL,Value=${{ vars.PROXY_BASE_URL }}")
+          [[ -n "${{ vars.DEBUG }}" ]] && ENV_VARS+=("Name=DEBUG,Value=${{ vars.DEBUG }}")
+          [[ -n "${{ vars.ACCOUNT_SIGNUP_ENABLED }}" ]] && ENV_VARS+=("Name=ACCOUNT_SIGNUP_ENABLED,Value=${{ vars.ACCOUNT_SIGNUP_ENABLED }}")
+          [[ -n "${{ vars.ACCOUNT_OWNERSHIP_ENABLED }}" ]] && ENV_VARS+=("Name=ACCOUNT_OWNERSHIP_ENABLED,Value=${{ vars.ACCOUNT_OWNERSHIP_ENABLED }}")
+          [[ -n "${{ vars.SOCIALACCOUNT_SIGNUP_ONLY }}" ]] && ENV_VARS+=("Name=SOCIALACCOUNT_SIGNUP_ONLY,Value=${{ vars.SOCIALACCOUNT_SIGNUP_ONLY }}")      
+          UPDATED_ENV_VARS=$(echo "$CURRENT_ENV_VARS" | jq -c '. + ['"$(IFS=, ; echo "${ENV_VARS[*]}")"']')      
+          UPDATED_ENV_VARS_STRING=$(echo "$UPDATED_ENV_VARS" | jq -r 'map("Name=" + .Name + ",Value=" + .Value) | join(" ")')
+          echo "Updating AWS App Runner service: $APP_RUNNER_SERVICE_NAME"
+          UPDATE_CMD="aws apprunner update-service --service-arn \"$SERVICE_ARN\" --source-configuration \"{
+            \\\"AuthenticationConfiguration\\\": {\\\"AccessRoleArn\\\": \\\"arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/AppRunnerECRAccessRole\\\"},
+            \\\"ImageRepository\\\": {
+              \\\"ImageIdentifier\\\": \\\"${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/hydroserver-api-${{ github.event.inputs.environment }}:latest\\\",
+              \\\"ImageRepositoryType\\\": \\\"ECR\\\"
+            }
+          }\" --environment-variables \"$UPDATED_ENV_VARS_STRING\""
+          eval $UPDATE_CMD
 
   teardown-hydroserver:
     needs: check-environment-variables
